# Generated by Django 3.1.7 on 2021-03-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='service',
            name='version',
        ),
    ]
