# Generated by Django 3.1.7 on 2021-03-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210312_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
