# Generated by Django 3.1.7 on 2021-03-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveServiceFilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='上传时间')),
                ('file_url', models.FileField(upload_to='Service_file')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_file',
            field=models.CharField(default='', max_length=100),
        ),
    ]
