# Generated by Django 3.1.7 on 2021-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210319_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_args',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='service_intro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='service_tool',
            field=models.IntegerField(default=-1),
        ),
    ]
