# Generated by Django 3.1.7 on 2021-04-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210426_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_tool',
            field=models.CharField(default='', max_length=100),
        ),
    ]
