# Generated by Django 3.1.7 on 2021-03-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_savetoolpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='dev_time',
            new_name='submit_time',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='name',
            new_name='tool_uploader',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='services',
            new_name='toolname',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='tools',
            new_name='toolpath',
        ),
    ]
