# Generated by Django 3.1.7 on 2021-03-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20210312_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savetoolpath',
            name='file_url',
            field=models.FileField(upload_to='Tool_upload'),
        ),
    ]
