# Generated by Django 3.1.7 on 2021-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20210319_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='toolDetail',
            field=models.TextField(default=''),
        ),
    ]
