# Generated by Django 3.1.7 on 2021-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_savefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveProblemZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='上传时间')),
                ('file_url', models.FileField(upload_to='ProblemZip')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
        migrations.AddField(
            model_name='problem',
            name='fileSetting_url',
            field=models.FileField(default='', upload_to='ProblemSetting'),
        ),
        migrations.AddField(
            model_name='problem',
            name='fileZip_url',
            field=models.FileField(default='', upload_to='ProblemZip'),
        ),
    ]
