# Generated by Django 3.1.7 on 2021-02-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20210225_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveProblemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='上传时间')),
                ('file_url', models.FileField(upload_to='ProblemSetting')),
            ],
        ),
    ]
