# Generated by Django 3.1.7 on 2021-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_saveproblemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='fileSetting_url',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='problem',
            name='fileZip_url',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.CharField(max_length=30),
        ),
    ]
