# Generated by Django 3.1.7 on 2021-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210226_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='user_submit',
            field=models.CharField(default='', max_length=30),
        ),
    ]
