# Generated by Django 3.1.7 on 2021-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_problem_user_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='subtype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
