# Generated by Django 3.1.7 on 2021-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taskNumber',
            field=models.IntegerField(default=0),
        ),
    ]
