# Generated by Django 3.1.7 on 2021-04-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210419_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualified',
            field=models.IntegerField(default=0),
        ),
    ]
